FROM lachlanevenson/k8s-kubectl:latest

LABEL "name"="Kubectl Action Builder"
LABEL "maintainer"="Sebastian Winkler <sebastian.winkler@slmn.de>"
LABEL "version"="0.0.1"

LABEL "com.github.actions.name"="Kubectl Action Builder"
LABEL "com.github.actions.description"="Actions with kubectl"
LABEL "com.github.actions.icon"="filter"
LABEL "com.github.actions.color"="blue"

ENTRYPOINT ["kubectl"]