apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: github-actions-test
  template:
    metadata:
      labels:
        app: github-actions-test
    spec:
      containers:
        - name: github-actions-test
          image: sekl/github-actions-test:latest
---
apiVersion: v1
kind: Service
metadata:
  name: github-actions-test-service
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8080
      name: http
  selector:
    app: github-actions-test
