FROM golang:1.11.4-stretch

LABEL "com.github.actions.name"="Go Action Builder"
LABEL "com.github.actions.description"="Actions for Go"
LABEL "com.github.actions.icon"="filter"
LABEL "com.github.actions.color"="blue"

ENTRYPOINT ["/bin/make"]