FROM golang:1.11.4-stretch

LABEL "name"="Go Action Builder"
LABEL "maintainer"="Sebastian Winkler <sebastian.winkler@slmn.de>"
LABEL "version"="0.0.1"

LABEL "com.github.actions.name"="Go Action Builder"
LABEL "com.github.actions.description"="Actions for Go"
LABEL "com.github.actions.icon"="filter"
LABEL "com.github.actions.color"="blue"

ENTRYPOINT ["/bin/make"]